version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask
    container_name: nginx_server
    restart: always 