version: '3'

services:
  flask:
    image: zhangzimin/docker-test-flask  
    container_name: flask_app
    restart: always

  nginx:
    image: zhangzimin/nginx  
    ports:
      - "80:80"
    depends_on:
      - flask
    container_name: nginx_server
    restart: always